In [1]:
# Домашнє завдання №1

In [2]:
## Завдання №1: Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

import numpy as np

a = np.arange(1, 11)

print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
## Завдання №2: Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

zero = np.zeros((3, 3), dtype=int)

print(zero)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
## Завдання №3: Створіть масив розміром 5x5, заповніть його випадковими цілими
## числами в діапазоні від 1 до 10 та виведіть його значення.
   
n = np.random.randint(1, 10, (5,5))

print(n)

[[5 5 8 3 2]
 [4 2 5 5 9]
 [4 5 8 1 3]
 [6 2 4 8 2]
 [4 1 6 8 8]]


In [5]:
## Завдання №4: Створіть масив розміром 4x4, заповніть його випадковими дійсними
## числами в діапазоні від 0 до 1 та виведіть його значення.

n = np.random.random((4, 4))

print(n)

[[0.5054027  0.3621003  0.59568873 0.35253559]
 [0.0699774  0.46369441 0.79909779 0.46804532]
 [0.32417059 0.62945585 0.37846001 0.81644225]
 [0.70533449 0.62070628 0.09021247 0.83302837]]


In [6]:
## Завдання №5: Створіть два одновимірних масиви розміром 5, заповніть їх випадковими 
## цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання,
## віднімання та множення.
        
a = np.random.randint(1, 10, 5)
b = np.random.randint(1, 10, 5)

print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)

[5 5 9 8 6]
[6 7 7 9 9]
[11 12 16 17 15]
[-1 -2  2 -1 -3]
[30 35 63 72 54]


In [7]:
## Завдання №6: Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

a = np.random.randint(1, 20, 7)
b = np.random.randint(1, 20, 7)

print(a)
print(b)
print(np.dot(a, b))

[ 9  1  8  3 14  4 15]
[ 5 17  1 15  3 19 15]
458


In [8]:
## Завдання №7: Створіть дві матриці розміром 2x2 та 2x3,
## заповніть їх випадковими цілими числами в діапазоні
## від 1 до 10 та перемножте їх між собою.

a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 3))

print(a)
print(b)

print(np.dot(a, b))

[[6 8]
 [8 3]]
[[6 6 1]
 [7 1 9]]
[[92 44 78]
 [69 51 35]]


In [9]:
## Завдання №8: Створіть матрицю розміром 3x3, заповніть її випадковими
## цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

a = np.random.randint(1, 10, (3, 3))
a_inv = np.linalg.inv(a)

print(a)
print(a_inv)

[[3 7 9]
 [1 9 6]
 [2 1 9]]
[[ 0.80645161 -0.58064516 -0.41935484]
 [ 0.03225806  0.09677419 -0.09677419]
 [-0.1827957   0.11827957  0.21505376]]


In [10]:
## Завдання №9: Створіть матрицю розміром 4x4, заповніть її випадковими 
## дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

n = np.random.random((4, 4))

print(n)
print(n.T)

[[0.4014683  0.58925246 0.35547193 0.47718521]
 [0.72063266 0.11803843 0.51222098 0.18546627]
 [0.26298406 0.29435939 0.70460725 0.53533276]
 [0.6260442  0.35071174 0.27458453 0.20861563]]
[[0.4014683  0.72063266 0.26298406 0.6260442 ]
 [0.58925246 0.11803843 0.29435939 0.35071174]
 [0.35547193 0.51222098 0.70460725 0.27458453]
 [0.47718521 0.18546627 0.53533276 0.20861563]]


In [11]:
## Завдання №10: Створіть матрицю розміром 3x4 та вектор розміром 4, 
## заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

a = np.random.randint(1, 10, (3,4))
b = np.random.randint(1, 10, 4)

print(a)
print(b)

print(np.dot(a, b))

[[1 1 2 8]
 [7 8 8 5]
 [2 7 2 1]]
[3 5 1 9]
[ 82 114  52]


In [12]:
## Завдання №11: Створіть матрицю розміром 2x3 та вектор розміром 3, 
## заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та 
## перемножте матрицю на вектор.

a = np.random.random((2, 3))
b = np.random.random(3)

print(a)
print(b)

print(np.dot(a, b))

[[0.64405368 0.35285072 0.91528778]
 [0.25164204 0.92144326 0.94909066]]
[0.51013704 0.48330412 0.64255487]
[1.08721246 1.18355208]


In [13]:
## Завдання №12: Створіть дві матриці розміром 2x2, заповніть їх випадковими 
## цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))

print(a)
print(b)

print(a * b)

[[1 4]
 [4 8]]
[[5 9]
 [3 9]]
[[ 5 36]
 [12 72]]


In [14]:
## Завдання №13: Створіть дві матриці розміром 2x2, заповніть їх випадковими 
## цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))

print(a)
print(b)

print(np.dot(a, b))

[[4 7]
 [7 9]]
[[9 2]
 [9 4]]
[[ 99  36]
 [144  50]]


In [15]:
## Завдання №14: Створіть матрицю розміром 5x5, заповніть її випадковими 
## цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

a = np.random.randint(1,100, (5, 5))

print(a)
print(a.sum())

[[ 8 38 14 41 92]
 [77 93 83 94 58]
 [59 36 12 47 21]
 [86 80 57 18 10]
 [95 44 50 78 89]]
1380


In [16]:
## Завдання №15: Створіть дві матриці розміром 4x4, заповніть їх випадковими
## цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

a = np.random.randint(1,10, (4, 4))
b = np.random.randint(1,10, (4, 4))

print(a)
print(b)

print(a - b)

[[2 7 4 2]
 [5 6 7 5]
 [9 2 7 7]
 [9 7 7 7]]
[[1 4 3 2]
 [4 2 6 1]
 [6 8 8 5]
 [7 4 9 7]]
[[ 1  3  1  0]
 [ 1  4  1  4]
 [ 3 -6 -1  2]
 [ 2  3 -2  0]]


In [17]:
## Завдання №16: Створіть матрицю розміром 3x3, заповніть її випадковими 
## дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, 
## що містить суму елементів кожного рядка матриці.

a = np.random.random((3, 3))
row_sums = np.sum(a, axis=1, keepdims=True)

print(a)
print(row_sums)

[[0.22143276 0.01750346 0.59093671]
 [0.21825642 0.26208422 0.70916374]
 [0.89349738 0.33464925 0.36218172]]
[[0.82987293]
 [1.18950438]
 [1.59032834]]


In [18]:
## Завдання №17: Створіть матрицю розміром 3x4 з довільними цілими числами
## і створінь матрицю з квадратами цих чисел.

a = np.random.randint(1, 30, (3, 4))

print(a)
print(a ** 2)
print(a * a)

[[26 28 23 29]
 [29 21 24 18]
 [15 14 26 14]]
[[676 784 529 841]
 [841 441 576 324]
 [225 196 676 196]]
[[676 784 529 841]
 [841 441 576 324]
 [225 196 676 196]]


In [19]:
## Завдання №18: Створіть вектор розміром 4, заповніть його випадковими
## цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

a = np.random.randint(1, 50, 4)

print(a)
print(a ** 0.5)
print(np.sqrt(a))

[22 41  5 12]
[4.69041576 6.40312424 2.23606798 3.46410162]
[4.69041576 6.40312424 2.23606798 3.46410162]
